# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='options',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_quote', models.CharField(max_length=250)),
                ('option_status', models.SmallIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='question_response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_time', models.DateTimeField()),
                ('option', models.ManyToManyField(null=True, to='quiz.options')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('sc', 'Single Correct'), ('mc', 'Multiple Correct')], default='sc', max_length=10)),
                ('question_title', models.TextField()),
                ('correct_message', models.TextField(null=True)),
                ('Incorrect_message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('beginning_quote', models.TextField(null=True)),
                ('end_quote', models.TextField(null=True)),
                ('duration', models.IntegerField(default=30)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='quiz_response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_of_attempt', models.DateTimeField(auto_now=True, null=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='question_response',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.questions'),
        ),
        migrations.AddField(
            model_name='question_response',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz_response'),
        ),
        migrations.AddField(
            model_name='options',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.questions'),
        ),
    ]
