# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-06 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20171007_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domainId', models.AutoField(primary_key=True, serialize=False)),
                ('domainName', models.CharField(max_length=250)),
                ('domainCode', models.CharField(default='00', max_length=2)),
            ],
        ),
    ]
